"""initial_schema

Revision ID: c37039a0fe5a
Revises: 
Create Date: 2026-04-03 03:06:20.571718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c37039a0fe5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('family_pin', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('account_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('can_read_transactions', sa.Boolean(), nullable=False),
    sa.Column('can_write_transactions', sa.Boolean(), nullable=False),
    sa.Column('can_delete_transactions', sa.Boolean(), nullable=False),
    sa.Column('can_read_bank_accounts', sa.Boolean(), nullable=False),
    sa.Column('can_write_bank_accounts', sa.Boolean(), nullable=False),
    sa.Column('can_delete_bank_accounts', sa.Boolean(), nullable=False),
    sa.Column('can_read_documents', sa.Boolean(), nullable=False),
    sa.Column('can_write_documents', sa.Boolean(), nullable=False),
    sa.Column('can_delete_documents', sa.Boolean(), nullable=False),
    sa.Column('can_read_family_members', sa.Boolean(), nullable=False),
    sa.Column('can_write_family_members', sa.Boolean(), nullable=False),
    sa.Column('can_delete_family_members', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_roles_owner_user_id'), 'account_roles', ['owner_user_id'], unique=False)
    op.create_table('bank_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('enrollment_token', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_bank_connection_provider_account')
    )
    op.create_index(op.f('ix_bank_connections_provider_account_id'), 'bank_connections', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_bank_connections_user_id'), 'bank_connections', ['user_id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_backup_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_passkeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.String(length=1024), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('aaguid', sa.String(length=255), nullable=True),
    sa.Column('transports', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_passkeys_credential_id'), 'user_passkeys', ['credential_id'], unique=True)
    op.create_table('user_totp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('account_accesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('sub_user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['account_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'sub_user_id', name='uq_access_owner_sub')
    )
    op.create_index(op.f('ix_account_accesses_owner_user_id'), 'account_accesses', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_account_accesses_sub_user_id'), 'account_accesses', ['sub_user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('member_relationship', sa.String(length=50), nullable=False),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_tax_dependent', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_household_id'), 'family_members', ['household_id'], unique=False)
    op.create_table('household_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('can_read_transactions', sa.Boolean(), nullable=False),
    sa.Column('can_write_transactions', sa.Boolean(), nullable=False),
    sa.Column('can_delete_transactions', sa.Boolean(), nullable=False),
    sa.Column('can_read_bank_accounts', sa.Boolean(), nullable=False),
    sa.Column('can_write_bank_accounts', sa.Boolean(), nullable=False),
    sa.Column('can_delete_bank_accounts', sa.Boolean(), nullable=False),
    sa.Column('can_read_documents', sa.Boolean(), nullable=False),
    sa.Column('can_write_documents', sa.Boolean(), nullable=False),
    sa.Column('can_delete_documents', sa.Boolean(), nullable=False),
    sa.Column('can_read_family_members', sa.Boolean(), nullable=False),
    sa.Column('can_write_family_members', sa.Boolean(), nullable=False),
    sa.Column('can_delete_family_members', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_roles_household_id'), 'household_roles', ['household_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_hsa_eligible', sa.Boolean(), nullable=True),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('hsa_category', sa.String(length=100), nullable=True),
    sa.Column('reimbursement_status', sa.String(length=20), nullable=True),
    sa.Column('reimbursed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'provider_transaction_id', name='uq_bank_txn_connection_provider_id')
    )
    op.create_index(op.f('ix_bank_transactions_connection_id'), 'bank_transactions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_family_member_id'), 'bank_transactions', ['family_member_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_is_hsa_eligible'), 'bank_transactions', ['is_hsa_eligible'], unique=False)
    op.create_index(op.f('ix_bank_transactions_provider_transaction_id'), 'bank_transactions', ['provider_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_table('family_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_username', sa.String(length=255), nullable=True),
    sa.Column('require_pin', sa.Boolean(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('household_role_id', sa.UUID(), nullable=True),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_role_id'], ['household_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_invites_token'), 'family_invites', ['token'], unique=True)
    op.create_table('household_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['household_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_membership')
    )
    op.create_index(op.f('ix_household_memberships_household_id'), 'household_memberships', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_memberships_user_id'), 'household_memberships', ['user_id'], unique=False)
    op.create_table('hsa_eligibility_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsa_eligibility_periods_family_member_id'), 'hsa_eligibility_periods', ['family_member_id'], unique=False)
    op.create_table('transaction_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_documents_transaction_id'), 'transaction_documents', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_documents_user_id'), 'transaction_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_documents_user_id'), table_name='transaction_documents')
    op.drop_index(op.f('ix_transaction_documents_transaction_id'), table_name='transaction_documents')
    op.drop_table('transaction_documents')
    op.drop_index(op.f('ix_hsa_eligibility_periods_family_member_id'), table_name='hsa_eligibility_periods')
    op.drop_table('hsa_eligibility_periods')
    op.drop_index(op.f('ix_household_memberships_user_id'), table_name='household_memberships')
    op.drop_index(op.f('ix_household_memberships_household_id'), table_name='household_memberships')
    op.drop_table('household_memberships')
    op.drop_index(op.f('ix_family_invites_token'), table_name='family_invites')
    op.drop_table('family_invites')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_provider_transaction_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_is_hsa_eligible'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_family_member_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_connection_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_household_roles_household_id'), table_name='household_roles')
    op.drop_table('household_roles')
    op.drop_index(op.f('ix_family_members_household_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_account_accesses_sub_user_id'), table_name='account_accesses')
    op.drop_index(op.f('ix_account_accesses_owner_user_id'), table_name='account_accesses')
    op.drop_table('account_accesses')
    op.drop_table('user_totp')
    op.drop_index(op.f('ix_user_passkeys_credential_id'), table_name='user_passkeys')
    op.drop_table('user_passkeys')
    op.drop_table('user_backup_codes')
    op.drop_table('households')
    op.drop_index(op.f('ix_bank_connections_user_id'), table_name='bank_connections')
    op.drop_index(op.f('ix_bank_connections_provider_account_id'), table_name='bank_connections')
    op.drop_table('bank_connections')
    op.drop_index(op.f('ix_account_roles_owner_user_id'), table_name='account_roles')
    op.drop_table('account_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.drop_table('registration_tokens')
    # ### end Alembic commands ###
