"""Initial migration - user authentication tables

Revision ID: 79163e061d18
Revises: 8f3ebfc10d22
Create Date: 2026-01-12 03:18:31.632554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79163e061d18'
down_revision: Union[str, None] = '8f3ebfc10d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
